#!/bin/bash
set -ux
Slack_Webhook_URL=https://hooks.slack.com/services/XXX/YYY/ZZZZZZZ
[ $# -ne 0 ] && MESSAGE=[$@] || MESSAGE="(slack_notif)"
curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"from Hilbert: '$MESSAGE'\"}" $Slack_Webhook_URL
